config/routes.rb
Rails.application.routes.draw do
  devise_for :pet_cares
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "adoptions#index"
  resources :adoptions, only: [:show] do
    patch 'adopt', on: :member
  end
  resources :animals, only: [:index]
end

app/models/adoption.rb
class Adoption
  attr_accessor :id, :title, :description, :animal_id, :animal_type, :animal_name, :age, :sex, :user_pet_care, :city

  def initialize(id:, title:, description:, animal_type:, animal_id:, animal_name: nil, age: nil, sex: nil, user_pet_care: nil, city:)
    @id = id
    @title = title
    @description = description
    @animal_id = animal_id
    @animal_type = animal_type
    @animal_name = animal_name
    @age = age
    @sex = sex
    @user_pet_care = user_pet_care
    @city = city
  end

  def self.all
    adoptions = []
    response = Faraday.get('http://localhost:4000/api/v1/adoptions')
    if response.status == 200
      data = JSON.parse(response.body)
      data.each do |adoption|
        adoptions << Adoption.new(id: adoption["id"], title: adoption['title'], animal_type: adoption['animal_type'],
                                  description: adoption['description'], animal_id: adoption['animal_id'], city: adoption['city'])
      end
    end
    adoptions
  end

  def self.find(id)
    adoption = ''
    response = Faraday.get("http://localhost:4000/api/v1/adoptions/#{id}")
    if response.status == 200
      data = JSON.parse(response.body)
      adoption = Adoption.new(id: data["id"], title: data['title'], animal_id: data['animal_id'], animal_type: data['animal_type'],
        description: data['description'], animal_name: data['animal_name'], age: data['age'],
        sex: data['sex'], user_pet_care: data['user_pet_care'], city: data['city'])
    end
    adoption
  end

end

app/models/animal.rb
class Animal
  attr_accessor :name, :animal_type, :sex, :city, :age

  def initialize(name:, animal_type:, sex:, city:, age:)
    @name = name
    @animal_type = animal_type
    @sex = sex
    @city = city
    @age = age
  end

  def self.all
    response = Faraday.get('http://localhost:4000/api/v1/animals')
    animals = []
    if response.status == 200
      animals_data = JSON.parse(response.body)
      animals_data.each do |animal|
        animals << Animal.new(name: animal['name'], animal_type: animal['animal_type'], sex: animal['sex'], city: animal['city'], age: animal['age'])
      end
    end
    animals
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pet_care.rb
class PetCare < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :cpf, format: {with: /(\A\d{3}\.\d{3}\.\d{3}\-\d{2}\z)|(\A\d{11}\z)/}
  validates :name, :city, presence: true
end

app/models/pet_care_animal.rb
class PetCareAnimal < ApplicationRecord
  belongs_to :pet_care
  validates :animal_id, presence: true
  validates :animal_id, numericality: {greater_or_equal_than: 0}
end

app/controllers/adoptions_controller.rb
class AdoptionsController < ApplicationController
  before_action :authenticate_pet_care!, only: [:show]

  def index
    @adoptions = Adoption.all
  end

  def show
    @adoption = Adoption.find(params[:id])
  end

  def adopt
    @adoption = Adoption.find(params[:id])
    PetCareAnimal.create!(pet_care: current_pet_care, animal_id: @adoption.animal_id)
    response = Faraday.patch("http://localhost:4000/api/v1/adoptions/#{params[:id]}/adopt")
    redirect_to root_path, notice: (JSON.parse(response.body))["message"]
  end
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController

  def index
    @animals = Animal.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from Faraday::ConnectionFailed, with: :connection_failed
  before_action :configure_permitted_parameters, if: :devise_controller?

  def connection_failed
    flash.now[:notice] = "A conexão com o sistema de adoções não aconteceu!"
    render 'adoptions/index'
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :city, :cpf])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/adoptions/index.html.erb
<h2>Me adota aí</h2>
<div>
  <%= link_to 'Todos os animais', animals_path %>
</div>
<% if !@adoptions.nil? && @adoptions.any? %>
  <% @adoptions.each do |adoption| %>
  <ul>
    <li><%= adoption.title %></li>
    <li><%= adoption.description %></li>
    <li><%= adoption.animal_type  %></li>
    <li><%= adoption.city %></li>
    <li><%= link_to "Acessar adoção", adoption_path(adoption.id) %>
  </ul>
  <% end %>
<% else %>
  <p>Não há adoções disponíveis.</p>
<% end %>

app/views/adoptions/show.html.erb
<h2>Adoção de <%="#{@adoption.animal_name}"%> </h2>

<div>
  <h3><%=@adoption.title%></h3>
  <p><%=@adoption.description%></p>
  <table>
    <tr>
      <th>Nome do animal</th>
      <th>Idade</th>
      <th>Tipo do animal</th>
      <th>Sexo</th>
      <th>Cuidador</th>
      <th>Cidade</th>

    </tr>
    <tr>
      <td><%=@adoption.animal_name%></td>
      <td><%=@adoption.age%></td>
      <td><%=@adoption.animal_type%></td>
      <td><%=@adoption.sex%></td>
      <td><%=@adoption.user_pet_care%></td>
      <td><%=@adoption.city%></td>
      <%= button_to "Adotar #{@adoption.animal_name}", adopt_adoption_path(@adoption.id), method: :patch %>
    </tr>
  </table>
</div>

app/views/animals/index.html.erb
<h2>Todos os animais cadastrados</h2>

<% if !@animals.nil? && @animals.any? %>
  <% @animals.each do |animal| %>
    <p><%= animal.name %> - <%= animal.animal_type %> | <%= animal.city %> |</p>
  <% end %>
<% else %>
  <p> Não há animais cadastrados </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Adoption App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <%= link_to 'Log in', new_pet_care_session_path %>
    <%= notice %>
    <%= yield %>
  </body>
</html>